### ISSUE TITLE
Matching stuff

### ISSUE THREAD

**Issue by njulius** [njulius/wild-bootstrap-matching#6]
Instead of storing an n by n matrix of almost entirely zeroes, use a logical matrix like this:

x treated treated treated
control true false true
control false false true
control false true false

where the logical values evaluate whether the control is the closest match to the treated (probably swap rows and columns from this but you get the point)

**Comment by grayclhn** [comment]
Not just a logical matrix, a **sparse** logical matrix --- that way it will just store the indexes of the true elements. They're defined in the `Matrix` package, which is included in R. I think `Matrix(false, nrows, ncols, sparse = TRUE)` should create the matrix but I'm not at a computer with R installed so I can't check right now.
