### ISSUE TITLE
genData() generates incorrect number of treated units

### ISSUE THREAD

**Issue by njulius** [njulius/wild-bootstrap-matching#8]
For example:

genData(8, (3/5), 5) generates 2 treated units and 6 untreated units, where it should generate 3 treated units and 5 untreated.

I suspect this is something to do with rounding in R, but don't know how to verify or fix.

**Comment by kdduncan** [comment]
Where is genData() defined? I couldn't find it to see what it looks like. Things like floor() and ceiling() provide fixed integer roundings. The other easy fix is to use number of observations & ratio combinations that don't generate rational numbers.

**Comment by njulius** [comment]
It is defined in dgp_function.R. I should probably just rename everything to the functions they define.

[edit] And the example given is a case where the number of observations and the ratio resolve to 3 treated units and 5 untreated, so its not an irrational number thing.

**Comment by grayclhn** [comment]
I just opened a pull request that should fix this error (https://github.com/njulius/wild-bootstrap-matching/pull/9). Long story short, `n1` is not automatically an integer and `sample` rounds down by default. If we explicitly round `n1` when we create it then `sample` no longer screws it up.

**Comment by njulius** [comment]
Thanks!
